### ISSUE TITLE
some markdown not rendering

### ISSUE THREAD

**Issue by ByronAhn** [Ovski4/jekyll-tabs#5]
Some of my markdown isn't rendering inside of a tab (where it renders fine outside of a tab).

The following code…
```
{% tabs A %}
{% tab A x %}
hi

- list item 1
- list item 2

bye
{% endtab %}
{% endtabs %}
```
… is rendered as shown in the image below (i.e. without the list items):
<img width="67" style="border:1px solid black;" src="https://user-images.githubusercontent.com/97747940/212574848-ee99a11a-6067-406b-b4e2-3d45f9d11c27.png">

**Comment by Ovski4** [comment]
The css file that is given in the example sets some style on lists. I just pushed [this commit ](https://github.com/Ovski4/jekyll-tabs/commit/1adfdf878f4d03f2d568b87b76b45a8f1ddba878) to fix this. So you can try updating the css file contents with the [latest version](https://raw.githubusercontent.com/Ovski4/jekyll-tabs/master/docs/tabs.css)

I don't think that's what you want, but you can also specify the markup language with a **md** block
 
````
{% tabs A %}
{% tab A x %}
hi

```md
- list item 1
- list item 2
```

bye
{% endtab %}
{% endtabs %}
````

I hope that helps

**Comment by ByronAhn** [comment]
Thanks for the quick patch! I don't work with CSS enough to know what fixes what, so that's a big help.

That said, I still have a problem: if a tab contains a list, any subsequent tabs come up as blank. So for example, with this code…
```
{% tabs A %}
{% tab A x %}
hi

- list item 1
- list item 2

bye
{% endtab %}
{% tab A y %}
hi
bye
{% endtab %}
{% tab A z %}
hi
bye
{% endtab %}
{% endtabs %}
```
… tab x is rendered correctly with a list, but tabs y and z are simply blank (not even containing "hi" or "bye").

Similarly, with this code…
```
{% tabs A %}
{% tab A x %}
hi
bye
{% endtab %}
{% tab A y %}
hi

- list item 1
- list item 2

bye
{% endtab %}
{% tab A z %}
hi
bye
{% endtab %}
{% endtabs %}
```
… tab x and tab y are correctly rendered, but tab z is simply blank.

<hr>

In case it's helpful, here is the .html file that's produced by this jekyll input (using your .css and .js files, as provided in this repo):
```
<!DOCTYPE html>
<html>

  <!-- Head -->
  <head><link rel="stylesheet" href="/assets/css/custom.css">
  </head>

  <!-- Body -->
  <body id="PageTop">
    <!-- Content -->
    <ul class="tab" data-tab="3eda3c8b-cccf-4f6a-a212-6afd4535d14c" data-name="A">
  
      <li class="active">
          <a href="#">x </a>
      </li>
  
      <li>
          <a href="#">y </a>
      </li>
  
      <li>
          <a href="#">z </a>
      </li>
  
</ul>
<ul class="tab-content" id="3eda3c8b-cccf-4f6a-a212-6afd4535d14c" data-name="A">
  
      <li class="active">
<p>hi
bye</p>
</li>
  
      <li>
<p>hi</p>

<ul>
  <li>list item 1</li>
  <li>list item 2</li>
</ul>

<p>bye</p>
</li>
  
      <li>
<p>hi
bye</p>
</li>
  
</ul>

  <script src="/assets/js/tabs.js"></script>
  </body>
</html>
```

**Comment by Ovski4** [comment]
I think issues come up because we have markdown embedded within a markdown file. There might be some ways to fix this but I don't have the time to spend time on this plugin right now.

I had a quick look, I find that removing the line break before the list fixes some things. i.e. from
```
{% tabs A %}
{% tab A x %}
hi
bye
{% endtab %}
{% tab A y %}
hi

- list item 1
- list item 2

bye
{% endtab %}
{% tab A z %}
hi
bye
{% endtab %}
{% endtabs %}
```

To

```
{% tabs A %}
{% tab A x %}
hi
bye
{% endtab %}
{% tab A y %}
hi
- list item 1
- list item 2

bye
{% endtab %}
{% tab A z %}
hi
bye
{% endtab %}
{% endtabs %}
```

It changes how the HTML is rendered (no idea why). Unlike you the tabs are rendered fine, but the content is wrong:

With the line break before the list:
<img width="218" alt="Screenshot 2023-01-18 at 3 10 16 PM" src="https://user-images.githubusercontent.com/1218714/213193174-1d3ed7c0-8e66-4e28-9ecb-358b964e91cd.png">

Versus without the line break:
<img width="218" alt="Screenshot 2023-01-18 at 3 10 08 PM" src="https://user-images.githubusercontent.com/1218714/213193168-1b2c4bc3-4381-4b86-a74f-0cc4f5217af6.png">



I can also reproduce with html. i.e.

```
hi

<ul>
<li>list item 1</li>
<li>list item 2</li>
</ul>
```
vs

```
hi
<ul>
<li>list item 1</li>
<li>list item 2</li>
</ul>
```

Does this help you to find a workaround?

**Comment by Ovski4** [comment]
I pushed some changes to the `tabs.js` file.
Just tested your markup and it's working fine now:

<img width="150" alt="Screenshot 2023-03-23 at 6 09 33 PM" src="https://user-images.githubusercontent.com/1218714/227399107-df68e78b-c629-4d2f-9661-6e58fb82c1e8.png">

So if you update the javascript with the latest version that should work now. 

I'll close this issue. Feel free the reopen it or create a new one if that does not work for you
